HPlusSports/HPlusSports.Web/ViewModels/CreateOrderViewModel.cs
using HPlusSports.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HPlusSports.Web.ViewModels
{
    public class CreateOrderViewModel
    {
        public List<SelectListItem> Products { get; set; }
        public List<string> SelectedProductCodes { get; set; }
        public List<SelectListItem> Customers { get; set; }
        public int CustomerId { get; set; }
        public List<SelectListItem> SalesPeople { get; set; }
        public int SalesPersonId { get; set; }

        public string ErrorMessage { get; set; }
        
    }
}

HPlusSports/HPlusSports.Web/ViewModels/EditSalespersonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HPlusSports.Models;
using System.ComponentModel.DataAnnotations;

namespace HPlusSports.Web.ViewModels
{
    public class EditSalespersonViewModel
    {
        Salesperson _person;
        public EditSalespersonViewModel()
        {
            _person = new Salesperson();
        }

        public EditSalespersonViewModel(Salesperson person)
        {
            _person = person;
        }

        public int Id { get { return _person.Id; }  set { _person.Id = value; } }
        [Required]
        public string FirstName { get { return _person.FirstName; } set { _person.FirstName = value; } }
        [Required]
        public string LastName { get { return _person.LastName; } set { _person.LastName = value; } }
        public string Email { get { return _person.Email; } set { _person.Email = value; } }
        public string Phone { get { return _person.Phone; } set { _person.Phone = value; } }

        public Salesperson GetPerson()
        {
            return _person;
        }
    }
}

HPlusSports/HPlusSports.Web/ViewModels/NewOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HPlusSports.Web.ViewModels
{
    public class NewOrder
    {
        public int CustomerId { get; set; }
        public int SalesPersonId { get; set; }
        
    }
}

HPlusSports/HPlusSports.Web/ViewModels/OrderListViewModel.cs
using HPlusSports.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HPlusSports.Web.ViewModels
{
    public class OrderListViewModel
    {
        public IList<Order> Orders { get; set; }
    }
}

HPlusSports/HPlusSports.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HPlusSports.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Error()
        {
            return View();
        }
    }
}

HPlusSports/HPlusSports.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using HPlusSports.Core;
using HPlusSports.Web.ViewModels;
using HPlusSports.Models;
using HPlusSports.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HPlusSports.Web.Controllers
{
    public class OrderController : Controller
    {
        IOrderService _orderService;
        IRepository<Customer> _customerRepo;
        IRepository<Product> _productRepo;
        ISalesPersonRepository _salesRepo;
        public OrderController(IOrderService orderService, IRepository<Customer> customerRepo, IRepository<Product> productRepo, ISalesPersonRepository salesRepo)
        {
            _orderService = orderService;
            _customerRepo = customerRepo;
            _productRepo = productRepo;
            _salesRepo = salesRepo;
        }

        public async Task<ActionResult> Index()
        {
            var vm = new OrderListViewModel();
            vm.Orders = await _orderService.GetOrdersWithCustomers();
            return View(vm);
        }

        public async Task<ActionResult> Customer(int id)
        {
            var vm = new OrderListViewModel();
            vm.Orders = await _orderService.GetCustomerOrders(id);
            return View("Index", vm);
        }

        public async Task<ActionResult> Create()
        {
            var vm = new CreateOrderViewModel()
            {
                Products = (await _productRepo.GetAll())
                    .Select(p => new SelectListItem() { Text = $"{p.ProductName} - {p.Variety}", Value = p.ProductCode }).ToList(),
                Customers = (await _customerRepo.GetAll())
                    .Select(c => new SelectListItem() { Text = $"{c.FirstName} {c.LastName}", Value = c.Id.ToString() }).ToList(),
                SalesPeople = (await _salesRepo.GetAll())
                    .Select(s => new SelectListItem() { Text = $"{s.FirstName} {s.LastName}", Value = s.Id.ToString() }).ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> CreateOrder(CreateOrderViewModel order)
        {
            var neworder = await _orderService.CreateOrder(
                order.CustomerId,
                order.SalesPersonId,
                order.SelectedProductCodes.Select(pc => Tuple.Create(pc, 1)).ToList());

            if (neworder.Id == 0)
            {
                order.ErrorMessage = "oops";
                return View("Create", order);
            }
            else
            {
                return Redirect("Index");
            }
        }

    }
}

HPlusSports/HPlusSports.Web/Controllers/SalesPersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using HPlusSports.Core;
using HPlusSports.Web.ViewModels;
using HPlusSports.Models;
using HPlusSports.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace HPlusSports.Web.Controllers
{
    public class SalesPersonController : Controller
    {
        ISalesPersonService _salesPersonService;
        ISalesPersonRepository _salesPersonRepo;
        public SalesPersonController(ISalesPersonService salesPersonServiceService, ISalesPersonRepository salesPersonRepo)
        {
            _salesPersonService = salesPersonServiceService;
            _salesPersonRepo = salesPersonRepo;
        }

        public async Task<ActionResult> Index()
        {
            var salesPeople = await _salesPersonRepo.GetWithOrders();
            return View(salesPeople);
        }

        public async Task<ActionResult> Edit(int Id)
        {
            var person = await _salesPersonRepo.GetByID(Id);

            return View(new EditSalespersonViewModel(person));
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditSalespersonViewModel vm)
        {
            //ValidateBusinessModel(vm.GetPerson(), ModelState);
            if (!ModelState.IsValid) return View(vm);

            await _salesPersonService.UpdateSalesPersonContact(vm.GetPerson());

            return Redirect("/SalesPerson/Index");
        }

        private void ValidateBusinessModel<T>(T model, ModelStateDictionary modelState)
        {
            var vc = new ValidationContext(model);
            var validations = new List<ValidationResult>();
            if (!Validator.TryValidateObject(model, vc, validations))
            {
                foreach (var validation in validations)
                    ModelState.AddModelError(validation.MemberNames.First(), validation.ErrorMessage);
            }
        }
    }
}

HPlusSports/HPlusSports.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h1>Hello</h1>

HPlusSports/HPlusSports.Web/Views/Order/Create.cshtml
@model HPlusSports.Web.ViewModels.CreateOrderViewModel
@{
    ViewBag.Title = "Create Order";
}
<h3>New Order</h3>

<form asp-action="CreateOrder" method="post">
    <div>
        <span><b>Select Customer</b></span>
        <select asp-for="CustomerId" asp-items="Model.Customers"></select>
    </div>
    <div style="clear:left">
        <span><b>Select Sales Person</b></span>
        <select asp-for="SalesPersonId" asp-items="Model.SalesPeople"></select>
    </div>
    <div style="clear:left">
        <div><b>Select Items</b></div>
        <select style="clear:both;height:10em;width:20em" asp-for="SelectedProductCodes" asp-items="Model.Products"></select>
    </div>
    <button type="submit">Create</button>
</form>
<div style="color:red">@Model.ErrorMessage</div>

HPlusSports/HPlusSports.Web/Views/Order/Index.cshtml
@model HPlusSports.Web.ViewModels.OrderListViewModel
@{ 
    ViewBag.Title = "Orders";
}
<h2>Orders</h2>
<h4><a asp-action="Create">Create New</a></h4>
<table style="border-spacing:1.5em;border-collapse:inherit">
    <thead>
        <tr>
            <td> Customer Name </td>
            <td> Total Due </td>
            <td> Status </td>
            <td> Order Date </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model.Orders)
        {
            <tr>
                <td><a asp-action="Customer" asp-route-id="@order.Customer.Id" >@order.Customer.FirstName @order.Customer.LastName</a></td>
                <td> @order.TotalDue?.ToString("f2") </td>
                <td> @order.Status </td>
                <td> @order.CreatedDate.ToString("d") </td>
            </tr>
        }
    </tbody>
</table>

HPlusSports/HPlusSports.Web/Views/SalesPerson/Edit.cshtml
@model HPlusSports.Web.ViewModels.EditSalespersonViewModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<form asp-action="Edit">
    <input asp-for="Id" type="hidden" />
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
    </div>
    <button type="submit">Update Team Member</button>
</form>

HPlusSports/HPlusSports.Web/Views/SalesPerson/Index.cshtml
@model IEnumerable<HPlusSports.Models.Salesperson>
@{ 
    ViewBag.Title = "Sales Team";
}
<h2>Sales Team</h2>
<table style="border-spacing:1.5em;border-collapse:inherit">
    <thead>
        <tr>
            <td> Name </td>
            <td> Email </td>
            <td> Orders </td>
            <td> State </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model)
        {
            <tr>
                <td><a asp-action="Edit" asp-route-id="@person.Id" >@person.FullName</a></td>
                <td> @person.Email </td>
                <td> @person.Order.Count() </td>
                <td> @person.SalesGroupState </td>
            </tr>
        }
    </tbody>
</table>

HPlusSports/HPlusSports.Web/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HPlusSports.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HPlusSports.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - HPlusSports.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

HPlusSports/HPlusSports.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HPlusSports.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HPlusSports.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Index">Orders</a></li>
                    <li><a asp-area="" asp-controller="SalesPerson" asp-action="Index">Sales Team</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - HPlusSports.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>